// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetAPI.Models;

public partial class LockingRestrictionTable
{
    public int Id { get; set; }

    public string TimeStartDay { get; set; }
    public string TimeStartHour { get; set; }
    public string TimeStartMinute { get; set; }
    public string TimeStopDay { get; set; }
    public string TimeStopHour { get; set; }
    public string TimeStopMinute { get; set; }


}