// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetAPI.Models;

public partial class LockingRestrictionTable
{
    public int Id { get; set; }

    public string TimeStart { get; set; }

    public string TimeStop { get; set; }

    public bool? LockUnlock { get; set; }
}