// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetAPI.Models;

public partial class PetActivityTable
{
    public string TimeStamp { get; set; }

    public string Id { get; set; }

    public bool? InOut { get; set; }

    public string Image { get; set; }
}