// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using PetAPI.Models;

namespace PetAPI.Data;

public partial class PetDatabaseContext : DbContext
{
    public PetDatabaseContext()
    {
    }

    public PetDatabaseContext(DbContextOptions<PetDatabaseContext> options)
        : base(options)
    {
    }

    public virtual DbSet<LockingRestrictionTable> LockingRestrictionTable { get; set; }

    public virtual DbSet<PetActivityTable> PetActivityTable { get; set; }

    public virtual DbSet<PetId> PetId { get; set; }

    public virtual DbSet<PetInformationTable> PetInformationTable { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=pet-server.database.windows.net;Initial Catalog=Pet-Database;Persist Security Info=True;User ID=drewshetler;Password=DT01-Dog-D00r");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<LockingRestrictionTable>(entity =>
        {
            entity.ToTable("Locking_Restriction_Table");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.TimeStart)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TimeStop)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<PetActivityTable>(entity =>
        {
            entity.HasKey(e => e.TimeStamp);

            entity.ToTable("Pet_Activity_Table");

            entity.Property(e => e.TimeStamp)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Image).IsUnicode(false);
        });

        modelBuilder.Entity<PetId>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("petId");

            entity.Property(e => e.Id)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<PetInformationTable>(entity =>
        {
            entity.ToTable("Pet_Information_Table");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Image).IsUnicode(false);
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}